.github/ISSUE_TEMPLATE /bug_report.md 
.github/ISSUE_TEMPLATE /feature_request.md
.github/pull_request_template.md
.github/workflows/ci.yml
.gitignore
CHANGELOG.md
CODEOWNERS
CONTRIBUTING.md
README.md
main.tf
versions.tf

Changes
- Added CI pipeline with GitHub actions for analyzing the modules
- Added issue and PR templates
- Added changelog, code owners, contributors guide etc.
- Added initial skeleton module

Initialize repository

---

examples/vpc-with-multiple-az/main.tf
examples/vpc-with-multiple-az/variables.tf
main.tf
modules/user_data/templates/install_graphdb.sh.tpl
modules/vm/main.tf
modules/vm/variables.tf
variables.tf

- added the custom AMI id and removed the option to use clean ubuntu
- extracted AMI id as parameter

GDB-8317 Modified the TF to use the custom GDB AMI

---

examples/vpc-with-multiple-az/main.tf
examples/vpc-with-multiple-az/variables.tf
main.tf
modules/config/versions.tf
modules/dns/versions.tf
modules/iam/main.tf
modules/iam/variables.tf
modules/iam/versions.tf
modules/load_balancer/versions.tf
modules/s3/main.tf
modules/s3/versions.tf
modules/user_data/main.tf
modules/user_data/templates/install_graphdb.sh.tpl
modules/user_data/variables.tf
modules/user_data/versions.tf
modules/vm/main.tf
modules/vm/variables.tf
modules/vm/versions.tf
tfsec.yml
variables.tf

Cleaned TFSec issues
- Configured tfsec to report issues from medium severity and above.
- Ignored some tfsec rules that do not apply for this module
- Removed unused policies and attachments (cloud_auto_join, inspector-policy)
- Tuned s3_crud for least privilege
- Added route53_instance_registration policy to replace full access attachment
- Organized iam/main.tf
- Reduced SSM policies
Added automatic AMI selection
- Added new variable graphdb_version that is used to select our AMI
- Added automatic architecture filtering based on the provided `instance_type`
- Removed unused variables in the user_data module
Additionally
- Added default tags in the main module
- Added versions.tf to each submodule. This effectively makes them a standalone modules that can be used without the root …

TES-233: Cleaned up code issues

---

modules/user_data/templates/install_graphdb.sh.tpl

Updated the EBS mounting to include the data folders of both GraphDB and its proxy.

TES-254: Persist GraphDB logs

---

main.tf
modules/graphdb/templates/04_gdb_backup_conf.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
variables.tf

Added a bool variable `deploy_backup` which allows you to deploy with or without backup module. 
GDB-9997
Added a bool variable `deploy_backup` 
Updated the user data script. 
N/A

GDB-9997 toggle on off backup

---

main.tf
modules/graphdb/main.tf
modules/graphdb/versions.tf
modules/monitoring/alarms.tf
modules/monitoring/main.tf
modules/monitoring/sns.tf
modules/monitoring/versions.tf
provider.tf

Fixed issues with tagging because of the two aliases related to the AWS provider.
[GDB-10130]
Fixed issues with tagging because of the two aliases related to the AWS provider.
[GDB-10130]: https://ontotext.atlassian.net/browse/GDB-10130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-10130] Improve tagging of resources and removed provider definitions that are not needed

---

README.md
main.tf
modules/graphdb/iam.tf
modules/graphdb/main.tf
modules/graphdb/templates/06_cloudwatch_setup.sh.tpl
modules/monitoring/alarms.tf
modules/monitoring/cloudwatch_agent_config.json.tpl
modules/monitoring/graphdb_dashboard.json
variables.tf

Fixed memory utilization alarm to be able to monitor the auto-scaling group.
Added option to enable detailed monitoring to be able to parse data every minute.
[GDB-9922]
Fixed memory utilization alarm to be able to monitor the auto-scaling group.
Added option to enable detailed monitoring to be able to parse data every minute.
[GDB-9922]: https://ontotext.atlassian.net/browse/GDB-9922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-9922] Fixed memory utilization alarm to monitor the Auto scaling group

---

modules/graphdb/variables.tf

Added missing variable in GraphDB module
Added missing variable in GraphDB module

[GDB-9922] Fixed missing variable

---

README.md
main.tf
modules/backup/main.tf
modules/backup/variables.tf
modules/backup_replication/main.tf
modules/backup_replication/outputs.tf
modules/backup_replication/variables.tf
modules/backup_replication/versions.tf
modules/graphdb/iam.tf
modules/graphdb/main.tf
modules/graphdb/outputs.tf
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
modules/load_balancer/main.tf
modules/load_balancer/variables.tf
modules/logging/main.tf
modules/logging/outputs.tf
modules/logging/variables.tf
modules/logging/versions.tf
modules/logging_replication/main.tf
modules/logging_replication/outputs.tf
modules/logging_replication/variables.tf
modules/logging_replication/versions.tf
modules/monitoring/availability_tests.tf
modules/vpc/main.tf
modules/vpc/variables.tf
provider.tf
variables.tf

Added toggle to enable/disable S3 Bucket access logging for the backup bucket.
Added new resources for the logging module
Added toggle to enable/disable LB access logs.
Added toggle to enable/disable VPC Flow Logs.
[GDB-10065]
[GDB-10066]
[GDB-10068]
[GDB-10067]
[GDB-10069]
[GDB-10071]
Added toggle to enable/disable S3 Bucket access logging for the backup bucket.
Added new resources for the logging module
Added toggle to enable/disable LB access logs.
Added toggle to enable/disable VPC Flow Logs.
[GDB-10065]: https://ontotext.atlassian.net/browse/GDB-10065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GDB-10066]: https://ontotext.atlassian.net/browse/GDB-10066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

[GDB-10087]AWS: Implement feature toggles for improved security and observability

---

README.md
main.tf
variables.tf

Fixed variables for the route53 availability port
Fixed variables for the route53 fqdn availability url
Fixed variables for the route53 availability port
Fixed variables for the route53 fqdn availability url

Fixed variable name for FQDN

---

modules/graphdb/templates/05_gdb_backup_conf.sh.tpl

Fixed issue when setting the cron job for the backup script
GDB-10518
Fixed issue when setting the cron job for the backup script
N/A

Fixed issue when setting the cron job for the backup script

---

CHANGELOG.md
README.md
variables.tf

Updated the GraphDB version to 10.7.2
Updated the GraphDB version to 10.7.2

Update GraphDB version to 10.7.2

---

CHANGELOG.md
README.md
variables.tf

Updated GDB version to 10.7.3
N/A
Updated GDB version to 10.7.3
N/A

updated GDB version to 10.7.3

---

modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl

Fixed issue with wrong protocol leading to nodes miscommunication
N/A
Changed internal protocol to HTTP when cluster
N/A

Fixed issue with wrong protocol leading to nodes miscommunication

---

CHANGELOG.md
README.md
variables.tf

Bumped GraphDB Version to 10.7.5
Bumped GraphDB Version to 10.7.5

Bumped GraphDB Version to 10.7.5

---

CHANGELOG.md
README.md
variables.tf

Update GraphDB default version to 10.7.6
Update GraphDB default version to 10.7.6

Update GraphDB default version to 10.7.6

---

CHANGELOG.md
README.md

Update GraphDB default version to 10.8.0
Update GraphDB default version to 10.8.0

Update GraphDB default version to 10.8.0

---

CHANGELOG.md
README.md
variables.tf

Updated default GraphDB version to 10.8.1
Updated default GraphDB version to 10.8.1

Updated default GraphDB version to 10.8.1

---

CHANGELOG.md
README.md
variables.tf

Updated the default GraphDB version to the latest patch version.

Update GraphDB version to 10.8.4

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/dns.tf
modules/graphdb/iam.tf
modules/graphdb/outputs.tf
modules/graphdb/templates/03_dns_provisioning.sh.tpl
modules/graphdb/templates/08_cluster_setup.sh.tpl
modules/graphdb/templates/09_node_join.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
variables.tf

- Added ability to use existing Route53 Zone
[GDB-11662]
- Added ability to use existing Route53 Zone
[GDB-11662]: https://ontotext.atlassian.net/browse/GDB-11662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-11662] Added ability to use existing Route53 zone

---

.terraform.lock.hcl
CHANGELOG.md
modules/backup/versions.tf
modules/backup_replication/versions.tf
modules/graphdb/variables.tf
modules/graphdb/versions.tf
modules/load_balancer/versions.tf
modules/logging/versions.tf
modules/logging_replication/versions.tf
modules/monitoring/versions.tf
modules/vpc/versions.tf
versions.tf

Update provider version in version.tf
[GDB-11727]
Update provider version in version.tf
[GDB-11727]: https://ontotext.atlassian.net/browse/GDB-11727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-11727] Updated provider version in versions.tf

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
variables.tf

Added the ability to provide additional custom user data scripts
[GDB-12003]
Added the ability to provide additional custom user data scripts
[GDB-12003]: https://graphwise.atlassian.net/browse/GDB-12003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added ability to provide additional custom user data scripts

---

CHANGELOG.md
README.md
variables.tf

Updated the default GraphDB version to the latest patch version.

Update GraphDB version to 10.8.5

---

modules/backup/main.tf
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl

Changed the backup script to permanently delete old backups.
GDB-12055
Changed the backup script to permanently delete old backups.
N/A

Added expiration for backup s3 bucket

---

README.md

Fixed the wrong GraphDB version in the README.md
Fixed the wrong GraphDB version in the README.md

Fixed wrong GraphDB version in the README.md

---

CHANGELOG.md
README.md
main.tf
outputs.tf
variables.tf

Added ability to use existing Load Balancer
[GDB-11173]
Added ability to use  Load Balancer
[GDB-11173]: https://graphwise.atlassian.net/browse/GDB-11173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-11173] Added ability to use existing Load Balancer

---

CHANGELOG.md
README.md
variables.tf

Updated GDB version to 11.0.1
N/A
Updated GraphDB default version to 11.0.1
N/A

Updated GDB version to 11.0.1

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/user_data.tf
modules/load_balancer/alb.tf
modules/load_balancer/main.tf
modules/load_balancer/nlb.tf
modules/load_balancer/outputs.tf
modules/load_balancer/variables.tf
modules/vpc/main.tf
variables.tf

* Added ability to choose between Application Load Balancer and Network Load Balancer
* Fixed issue where the script for changing the permissions of the AWS CLI executable will lead to failure of the user-data scripts
[GDB-12213]
* Added ability to choose between Application Load Balancer and Network Load Balancer
* Fixed issue where the script for changing the permissions of the AWS CLI executable will lead to failure of the user-data scripts
[GDB-12213]: https://graphwise.atlassian.net/browse/GDB-12213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-12213] Add ability select Load Balancer type

---

CHANGELOG.md
README.md
variables.tf

Updated the default GraphDB version to the latest patch version for 10.x

Update GraphDB version to 10.8.7

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/templates/00_functions.sh
modules/graphdb/templates/01_wait_node_count.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
variables.tf

- Added flag to disable enable_asg_wait function
[GDB-12377]
- Added flag to disable enable_asg_wait function
[GDB-12377]: https://graphwise.atlassian.net/browse/GDB-12377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-12377] Added flag to disable enable_asg_wait function

---

CHANGELOG.md
README.md
modules/graphdb/templates/01_wait_node_count.sh.tpl
variables.tf

- Enable wait_asg function for single node deployments
[GDB-12970]
- Enable wait_asg function for single node deployments
[GDB-12970]: https://graphwise.atlassian.net/browse/GDB-12970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-12970] Enable wait_asg function for single node deployments

---

CHANGELOG.md
README.md
variables.tf

Bumped GDB version to 11.1.1
N/A
Bumped GDB version to 11.1.1
N/A

Bumped GDB version to 11.1.1
