modules/iam/main.tf

Added a new action `s3:GetAccelerateConfiguration` to the permissions of the backup user. This action allows the user to retrieve the configuration of Amazon S3 Transfer Acceleration for a bucket.
TES-246
- Added the `s3:GetAccelerateConfiguration` action to the permissions of the backup user.
N/A

Added s3:GetAccelerateConfiguration action to the backup user

---

modules/user_data/templates/install_graphdb.sh.tpl

Data disk was not mounted to the EC2 instance after reboot. 
https://ontotext.atlassian.net/browse/TES-268
Added script, which adds the data volume to fstab
Added checks if the volume is already mounted or present in the fstab file. 
N/A

Added script, which adds the data volume to fstab

---

modules/iam/main.tf

Added additional actions to the S3 policy document to handle the cases where GraphDB needs to abort and clean up multipart uploads.
GDB-8401

Extend s3 policy document

---

.editorconfig
examples/vpc-with-multiple-az/main.tf
examples/vpc-with-multiple-az/monitoring/README.md
examples/vpc-with-multiple-az/monitoring/main.tf
examples/vpc-with-multiple-az/monitoring/variables.tf
examples/vpc-with-multiple-az/monitoring/versions.tf
modules/iam/main.tf
modules/user_data/main.tf
modules/user_data/templates/start_graphdb.sh.tpl
variables.tf

GDB-286 initial commit with tf new module

---

modules/user_data/main.tf

Reducing the jvm_max_memory, because as it is set leaves only 4gb for the off-heap, classes loaded, the OS itself or stacks of threads or the memory used for the JIT for instance. 
N/A
The heap memory will now take total VM memory minus 10GB.
N/A

Reduced the jvm_max_memory

---

main.tf
modules/config/config.tf
modules/config/main.tf
modules/config/variables.tf
modules/user_data/templates/03_gdb_conf_overrides.sh.tpl
modules/user_data/templates/04_gdb_backup_conf.sh.tpl
modules/user_data/templates/06_cloudwatch_setup.sh.tpl
modules/user_data/templates/07_cluster_setup.sh.tpl
variables.tf
versions.tf

Added random password and cluster token generate for GraphDB Admin password.
Removed some validations that were not needed here.
https://ontotext.atlassian.net/browse/GDB-9776

GDB-9776: Add random password and cluster secret

---

main.tf
modules/config/main.tf
modules/config/variables.tf
modules/monitoring/main.tf
modules/user_data/templates/03_gdb_conf_overrides.sh.tpl
modules/user_data/templates/06_cloudwatch_setup.sh.tpl
modules/user_data/templates/07_cluster_setup.sh.tpl
modules/vm/iam.tf
modules/vm/main.tf
modules/vm/variables.tf
variables.tf

Added two SSM Parameters to the parameter store. Changed the user-data script to use them
Added check if the /CWAgent/Config exists in ssm before applying it.
Made the cluster setup script exit if the cluster creation fails for unknown reason.
Added ssm:DescribeParameters permissions to the iam role
Moved graphdb_properties_path and graphdb_java_options to root level
Fixed type-o in monitoring_sns_protocol description
GDB-9774

Add SSM parameters

---

CHANGELOG.md
main.tf
modules/graphdb/templates/01_disk_management.sh.tpl
modules/graphdb/templates/02_dns_provisioning.sh.tpl
modules/graphdb/templates/03_gdb_conf_overrides.sh.tpl
modules/graphdb/templates/04_gdb_backup_conf.sh.tpl
modules/graphdb/templates/06_cloudwatch_setup.sh.tpl
modules/graphdb/templates/07_cluster_setup.sh.tpl
modules/graphdb/templates/08_node_rejoin.sh.tpl
modules/graphdb/templates/README.md
modules/graphdb/user_data.tf
modules/graphdb/variables.tf

Added check if 1 node is deployed, don't setup DNS records and attempt to create cluster
- Implemented cluster rejoin procedure
- Introduced stable network names
- Improved cluster creations.
- Refactored the attach disk logic to handle multiple disks in the same AZ. 
- Added README and diagrams displaying the logic in the scripts.
- Improved logging. 
- Other improvements
GDB-9900
- Refactored the user data scripts 
- Added node rejoin
- Included deploy_monitoring and deploy_backup variables to the graphdb module to be used in the user data scripts. 
- Added README and diagrams
- Renamed some variables to be descriptive.
N/A

GDB-9900 Cluster rejoin

---

README.md
modules/graphdb/main.tf

GDB-10095 Introduced update_default_version to the aws_launch_template
This way the latest launch template will be the default instead of the initially created one.
This is required when performing manual update of the instances as described in https://graphdb.ontotext.com/documentation/10.6/aws-deployment.html#updating-graphdb-configurations-and-versions 
GDB-10095
Added update_default_version
Changed the way the latest version of the launch_template is obtained in tf. 
N/A

GDB-10095 Introduced update_default_version to the aws_launch_template

---

.terraform.lock.hcl
README.md
main.tf
modules/graphdb/iam.tf
modules/graphdb/main.tf
modules/graphdb/outputs.tf
modules/graphdb/templates/00_wait_node_count.sh.tpl
modules/graphdb/templates/01_disk_management.sh.tpl
modules/graphdb/templates/02_dns_provisioning.sh.tpl
modules/graphdb/templates/07_cluster_setup.sh.tpl
modules/graphdb/templates/08_node_join.sh.tpl
modules/graphdb/templates/README.md
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
modules/load_balancer/variables.tf
variables.tf
versions.tf

Enabled instance refresh for GDB ASG 
GDB-10121
Added `ec2:DescribeInstanceStatus` role to `graphdb_instance_volume` policy
Fixed a type-o in `graphdb_auto_scaling_group`
Added `instance_refresh` to `aws_autoscaling_group`
Added new script modules/graphdb/templates/00_wait_node_count.sh.tpl which handles instance refresh to not duplicate volumes or DNS records.
Updated `modules/graphdb/templates/01_disk_management.sh.tpl` to handle rerunning the user data script on reboot. 
Enabled the user data scripts to be ran on EC2 reboot, stop/start, etc. 
Changed `lb_health_check_path` to `/protocol` instead of `/rest/cluster/node/status`
Fixed issue with creating new disks when disk was already attached.
Updated README.md
Added checks for cluster quorum.
Moved the logic for disk mounting so there …

GDB-10121 Enabled Instance Refresh for the ASG instances

---

modules/graphdb/templates/01_wait_node_count.sh.tpl
modules/graphdb/templates/08_cluster_setup.sh.tpl

Fixed issue when waiting for available volume
Fixed an issue when pinging GraphDB where the VM does not respond when pinged without http://
GDB-10286
Fixed issue when waiting for available volume
Fixed an issue when pinging GraphDB where the VM does not respond when pinged without http://
N/A

Fixed issue when waiting for available volume

---

.terraform.lock.hcl
README.md
main.tf
modules/graphdb/main.tf
modules/graphdb/variables.tf
variables.tf

Added support for custom owner ID for the AMIs and added new default owner ID
[GDB-10293]
- Added new default AMI owner ID
- Added ability to specify custom owner ID via variable
[GDB-10293]: https://ontotext.atlassian.net/browse/GDB-10293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-10293] Added support for custom owner ID for the AMIs and added new default owner ID

---

.terraform.lock.hcl
README.md
main.tf
variables.tf

Added support to use existing VPC and subnets.
If you specify VPC ID and subnets IDs it will use them to deploy the GraphDB cluster.
[GDB-10405]
Added two variables for the subnet IDs in public and private networks.
Added conditions to check if there is specified VPC ID and subnet IDs. If they are set it will deploy the GraphDB cluster in that VPC and subnets.
[GDB-10405]: https://ontotext.atlassian.net/browse/GDB-10405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-10405]Added support to use existing VPC and subnets

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/nsg.tf
modules/graphdb/templates/00_functions.sh
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
modules/graphdb/templates/08_cluster_setup.sh.tpl
modules/graphdb/templates/09_node_join.sh.tpl
modules/graphdb/templates/10_start_single_graphdb_services.sh.tpl
modules/graphdb/user_data.tf
modules/load_balancer/main.tf
modules/load_balancer/variables.tf
modules/monitoring/alarms.tf
modules/monitoring/availability_tests.tf
modules/monitoring/variables.tf
modules/vpc/main.tf
modules/vpc/variables.tf

Added the ability to deploy a single node GraphDB
GDB-10418 
Added support for single node deployment. 
Removed hardcoded values for DNS zone in userdata scripts
Updated the NSGs ports based on graphdb_node_count
Updated user_data.tf
Changed the name of the LB target group to avoid conflicts when scaling from 1 to 3 AZs
Updated the monitoring, to not deploy cluster alarms when a single node is deployed
Updated the availability_tests
Updated how the VPC azs are calculated based on the graphdb_node_count
Added calculations for the subnets based on the graphdb_node_count
N/A

GDB-10418 Single Node Deployment

---

CHANGELOG.md
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl

Added proper escaping in the backup user data script
N/A
Added proper escaping in the backup user data script
N/A

Added proper escaping in the backup user data script

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
variables.tf

Fixed backup script variables
Fixed Route53 availability check
Fixed Route53 availability port
Fixed backup script variables
Fixed Route53 availability check
Fixed Route53 availability port

Fixed issues with backup and monitoring

---

.terraform.lock.hcl
CHANGELOG.md
README.md
main.tf
modules/graphdb/config.tf
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
modules/load_balancer/main.tf
modules/load_balancer/variables.tf
variables.tf

Fixed issues related to single node deployment
GDB-10523
* Removed unused variables
* Fixed graphdb.properties values for single node deployment
* Removed calculation of `lb_tls_enabled` in the LB module as it is calculated in the main.tf
* Replaced `monitoring_route53_healtcheck_fqdn_url` with `graphdb_external_address` as it is the same URL.
* Removed `monitoring_route53_healtcheck_fqdn_url` variable
* Introduced new variable `graphdb_external_address`
N/A

Fixed issues related to single node deployment

---

.gitignore
CHANGELOG.md
README.md
variables.tf

Updated default GraphDB version to 10.8.0
Updated default GraphDB version to 10.8.0

Updated default GraphDB version to 10.8.0

---

modules/graphdb/main.tf
modules/graphdb/templates/00_functions.sh
modules/graphdb/templates/01_wait_node_count.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf

- Added a condition to check if the node count equals the desired count.
- Added instance policy
[GDB-11356]
- Added a condition to check if the node count equals the desired count.
- Added instance policy
[GDB-11356]: https://ontotext.atlassian.net/browse/GDB-11356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added Instance Maintenance Policy

---

.terraform.lock.hcl
CHANGELOG.md
README.md
main.tf
modules/graphdb/dns.tf
modules/graphdb/iam.tf
modules/graphdb/nsg.tf
modules/graphdb/outputs.tf
modules/graphdb/templates/00_functions.sh
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
modules/graphdb/templates/08_cluster_setup.sh.tpl
modules/graphdb/templates/10_start_single_graphdb_services.sh.tpl
modules/graphdb/user_data.tf
modules/load_balancer/main.tf
modules/monitoring/alarms.tf

GDB-11661 Skipped provisioning of Route53 hosted zone when a single node is deployed
GDB-11661 
* Made the Route53 hosted zone deployment dynamic based on `graphdb_node_count`. 
* Updated user data scripts to not run DNS configurations if a single node is deployed. 
* Changed the availability test endpoint address when deploying a single node. 
N/A

GDB-11661 Skipped provisioning of Route53 hosted zone when a single node is deployed

---

.gitignore
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl

Parses GDB_JAVA_OPTS variable from /etc/graphdb/graphdb.env, instead of source the file
[GDB-11623](https://ontotext.atlassian.net/browse/GDB-11623)
Changes `04_gdb_conf_overrides.sh.tpl` to parse `/etc/graphdb/graphdb.env` and modify GDB_JAVA_OPTS inline  
[GDB-11623]: https://ontotext.atlassian.net/browse/GDB-11623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-11623] Parse /etc/graphdb/graphdb.env and modify GDB_JAVA_OPTS inline

---

modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl

Fixes a typo in `04_gdb_conf_overrides.sh.tpl`, and an invalid `grep` check which fails to configure GraphDB. Regressions introduced in https://github.com/Ontotext-AD/terraform-aws-graphdb/pull/82
[GDB-11623](https://ontotext.atlassian.net/browse/GDB-11623)
- Fixes the typo, which would occur if no `GDB_JAVA_OPTS` are set in `/etc/graphdb/graphdb.env`  (this case is not reachable by default)
- Fixes the reordering of `grep` logic to check if `GDB_JAVA_OPTS` is set.
[GDB-11623]: https://ontotext.atlassian.net/browse/GDB-11623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixes typo in 04_gdb_conf_overrides.sh.tpl. Reorder check

---

CHANGELOG.md
modules/graphdb/iam.tf
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl

Refactors graphdb -> graphdb_iam.tf to restrict `graphdb_instance_ssm` policy resource to only SSM resources part of the deployment
[GDB-11619](https://ontotext.atlassian.net/browse/GDB-11619)
1. Set the resources for `graphdb_instance_ssm` to `"arn:aws:ssm:${var.aws_region}:${var.aws_subscription_id}:/${var.resource_name_prefix}/graphdb/*"` which should limit to any resources defined in the `graphdb` logical group.
[GDB-11619]: https://ontotext.atlassian.net/browse/GDB-11619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GDB-11619] Restrict graphdb_instance_ssm to resources part of GDB deployment

---

main.tf
modules/graphdb/templates/01_wait_node_count.sh.tpl
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
modules/monitoring/alarms.tf
modules/monitoring/cloudwatch_agent_config.json.tpl
modules/monitoring/variables.tf

Reworked memory alarms for GDB instances in ASG
The memory alarm now tracks the GDB heap memory instead of the VM total memory 
Enabled gathering of `mem_total` metric by CW Agent
GDB-11905 
Reworked memory alarms for GDB instances in ASG
Updated the `cloudwatch_agent_config.json.tpl` to include `mem_total`
Updated user data scripts to set hostname if single node deployment. 
N/A

GDB-11905 Reworked memory alarms for GDB instances in ASG

---

CHANGELOG.md
README.md
main.tf
modules/monitoring/availability_tests.tf
modules/monitoring/graphdb_dashboard_no_availability.json
modules/monitoring/main.tf
modules/monitoring/variables.tf
variables.tf

Added a toggle for the Availability tests in CloudWatch
GDB-11915 
* Added a toggle for the Availability tests in CloudWatch
* Introduced a new variable `monitoring_enable_availability_tests` 
* Added a dashboard without the availability monitoring widget
N/A

GDB-11915 Added a toggle for the Availability tests in CloudWatch

---

CHANGELOG.md
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
modules/graphdb/user_data.tf

For security purposes, make AWS cli, located in `/usr/local/aws-cli` accessible only by `root` user
[GDB-11621](https://ontotext.atlassian.net/browse/GDB-11621)
Make `/usr/local/aws-cli` accessible only by the root user
[GDB-11621]: https://ontotext.atlassian.net/browse/GDB-11621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove access to AWS cli for users other than root

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/iam.tf
modules/graphdb/main.tf
modules/graphdb/templates/02_disk_management.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
variables.tf

Add restrictions on ec2:CreateTags, ec2:CreateVolume and ec2:AttachVolume. Add deploy_tag variable
Add restrictions on ec2:CreateTags, ec2:CreateVolume and ec2:AttachVolume. Add deploy_tag variable
[https://ontotext.atlassian.net/browse/GDB-11618](GDB-11618)
- Add restrictions on ec2:CreateTags
- Add restrictions on ec2:CreateVolume
- Add restrictions on ec2:AttachVolume. 
- Add deploy_tag variable

Add restrictions on ec2:CreateTags, ec2:CreateVolume and ec2:AttachVolume. Add deploy_tag variable

---

modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
modules/graphdb/user_data.tf

Run cronjob as root user to make sure that the backup rotation works correctly (without exposing aws cli to low-priv users)
[GDB-11621](https://graphwise.atlassian.net/browse/GDB-11621)
* Run cronjob as root
* Make sure backup log file is initialized correctly during provision
[GDB-11621]: https://graphwise.atlassian.net/browse/GDB-11621?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GDB-11621 Run cronjob as root, to make sure that backup rotation works correctly.

---

CHANGELOG.md
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl

Version 10.8.0 unified the local and cloud backup and restore endpoints to use the same JSON structure for the request payload.
The endpoint was also updated to use a multipart content type and the old JSON endpoint was deprecated.
GDB-12092
* update backup script to use multipart endpoint as described [here](https://graphdb.ontotext.com/documentation/10.8/backup-and-restore.html#creating-a-cloud-backup)

Update backup script to use multipart endpoint

---

CHANGELOG.md
README.md
main.tf
modules/graphdb/main.tf
modules/graphdb/templates/08_cluster_setup.sh.tpl
modules/graphdb/variables.tf
variables.tf

GDB-12101 Updated the logic to properly form a cluster when scaling from 1 to 3 or more nodes.
Removed the `asg_enable_instance_refresh` functionality. Updated the CHANGELOG.md
GDB-12101
Removed the  `asg_enable_instance_refresh` functionality. 
Changed the logic of forming the cluster when scaling from 1 to 3 or more nodes to correctly handle the cluster formation. 
N/A

GDB-12101 Updated the logic to properly form a cluster when scaling from 1 to 3 or more nodes.

---

.terraform.lock.hcl
CHANGELOG.md
README.md
main.tf
modules/backup/main.tf
modules/graphdb/iam.tf
modules/graphdb/main.tf
modules/graphdb/templates/04_gdb_conf_overrides.sh.tpl
modules/graphdb/templates/05_gdb_backup_conf.sh.tpl
modules/graphdb/templates/08_cluster_setup.sh.tpl
modules/graphdb/variables.tf
variables.tf

- Added ability to provide additional ARNs for IAM Policies
- Added ability to get dynamic http protocol for gdb_conf_overrides based on the lb_certificate_arn
- Removed the `asg_enable_instance_refresh` property and the instance auto-refresh functionality.
- Fixed issue where the cluster was not formed when scaling from 1 node to 3 or more nodes.
- Updated backup script to use the new multipart endpoint
- Updated backup script to permanently delete old backups
[GDB-12038]
[GDB-12104]
[GDB-12101]
[GDB-12055]
[GDB-12092]
- Added ability to provide additional ARNs for IAM Policies
- Added ability to get dynamic http protocol for gdb_conf_overrides based on the lb_certificate_arn
- Removed the `asg_enable_instance_refresh` property and the instance auto-refresh functionality.
- Fixed issue …

Features for 1.5.0

---

README.md

When scaling down to single node, terraform tries to delete subnets, but it fails because the subnets are used by the instances.
This is now added as a note in the readme with a short manual procedure.
GDB-12193

add note about scaling down a cluster to single node

---

CHANGELOG.md
README.md
main.tf
modules/monitoring/alarms.tf
modules/monitoring/availability_tests.tf
modules/monitoring/cmk.tf
modules/monitoring/variables.tf
provider.tf
variables.tf

* Fixed CMK Key Access Policy so Cloudwatch Service can publish to the SNS topic [Cloudwatch Alarms via SNS](https://repost.aws/knowledge-center/cloudwatch-configure-alarm-sns)
* Removed monitoring_actions_enabled because it's enabled by default in the provider if action is specified.
* Introduced new variables app_name and environment name, so if you deploy several deployments in one account, to be able to deploy different CMK keys.
* Moved the CMK Alias generation in a local variable so it can be dynamically generated.
[GDB-12318]
* Fixed CMK Key Access Policy so Cloudwatch Service can publish to the SNS topic [Cloudwatch Alarms via SNS](https://repost.aws/knowledge-center/cloudwatch-configure-alarm-sns)
* Removed monitoring_actions_enabled because it's enabled by default in the …

[GDB-12318] Fix permissions issue with CloudWatch Alarms and change SNS CMK key alias

---

CHANGELOG.md
README.md
main.tf
modules/backup/cmk.tf
modules/graphdb/cmk-ebs.tf
modules/graphdb/cmk-parameter-store.tf
modules/graphdb/templates/00_functions.sh
modules/graphdb/templates/01_wait_node_count.sh.tpl
modules/graphdb/user_data.tf
modules/graphdb/variables.tf
modules/monitoring/alarms.tf
modules/monitoring/cmk.tf
modules/monitoring/variables.tf
variables.tf

- Enabled dynamic inclusion of IAM group members as KMS administrators for easier management and access control.
- Users can now customize CPU and Memory Utilization thresholds for CloudWatch alarms, allowing fine-tuned scaling behavior. 
- Introduced a flag to enable or disable the ASG_WAIT_NODE function, offering flexibility for single-node or fast-scaling environments.
[GDB-12341]
[GDB-12376]
[GDB-12377]
- Added ability to use IAM Group for KMS Key Admin
- Added ability to change threshold for CPU, Mem Utilization alarms
- Introduced ability to disable/enable the ASG_WAIT_NODE function
[GDB-12341]: https://graphwise.atlassian.net/browse/GDB-12341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GDB-12376]: …

Release v2.2.0

---

CHANGELOG.md
README.md
variables.tf

Updated the default GraphDB version to the latest patch version for 10.x

GDB-12470: Update GraphDB version to 10.8.8
